name: Vault Read secrets
branding:
  icon: 'unlock'
  color: 'blue'
inputs:
  secrets:
    description: 'A comma-delimited list of secret keys to retrieve from VAULT. Those elements will be also available as outputs'
    required: true
  env-var:
    description: 'A flag to expose the secrets as $\{{ env.SECRET_KEY }}'
    required: false
    default: '1'
runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_SECRETS: ${{ inputs.secrets }}
    INPUT_ENV_VAR: ${{ inputs.env-var }}